### ISSUE TITLE
Bounding boxes do not take in account the mesh's rotation

### ISSUE THREAD

**Issue by msanterre** [jeromeetienne/microphysics.js#4]
This can easily be duplicated by having a ball hit a rotated cube. The ball will enter the cube's mesh until it hits the non-rotated bounding box.

**Comment by jeromeetienne** [comment]
What is describe is correct. O. The pther hand, to take into account the mrsh rotation isnt trivial as there are multiple possible answers. On the other hand if you use threex helper, it is possible to specify a specific geometry. So you can specify how the object will react from a physic point of view independantly from the object itself

http://learningthreejs.com/blog/2011/11/02/lets-make-a-3d-game-helper-for-microphysics-js/

**Comment by msanterre** [comment]
I think it's more of a problem in the underlying library used (the codeflow one). You can only build AABB objects using the size and position of an geometry. I guess you could use a sphere geometry to bound the cube so that the corners collide, but it would make the flat surface collisions premature and would only work for cubes, not planes or rectangles.

For now I'm thinking of including a rotation vector variable in the AABB class and rotating the bounding box accordingly. I'm fairly new at this, so it might not be the best solution.

I'm currently reading up on the physics.js code. I'll try to fix it and commit the fix if possible.

**Comment by jeromeetienne** [comment]
a pull request is more than welcome. 

nevertheless be aware current behavior isnt a bug, it is a known limitation. subtle difference :)
